# This is a basic workflow to help you get started with Actions

name: Breaking Changes

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the select branch(es)
  # push:
  #   branches: [develop]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-for-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current branch
        uses: actions/checkout@v2
        with:
          path: current
      - name: Check out production branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: prod
      - name: Run OpenAPI Diff (from CURRENT revision)
        continue-on-error: true
        uses: mvegter/openapi-diff-action@v0.23.3
        with:
          head-spec: current/reference/api.v1.yaml
          base-spec: prod/reference/api.v1.yaml
      - name: Get PROD Version From .ENV
        
        uses: falti/dotenv-action@v0.2.5
        with:
          log-variables: true
          path: prod/.env
        id: prod-dotenv
      - name: Bump release version
        
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.prod-dotenv.outputs.version }}
          version-fragment: 'major'
      - name: Get CURRENT Version From .ENV
        
        uses: falti/dotenv-action@v0.2.5
        with:
          log-variables: true
          path: current/.env
        id: curr-dotenv
      - name: SEMVER STRING
        
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.curr-dotenv.outputs.version }}
          regex: '^([${{ steps.bump_version.outputs.next-version }}]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'
      - name: Version Is correct
        if: ${{ steps.regex-match.outputs.match == '' }}
        run: exit 1